### PR TITLE
Change format eslint to yaml, update dependencies and devDependencies

### PR DESCRIPTION
**Pull request by brutalcrozt**
loadash updated to 4.3.0
eslint v.2.0.0
---

with this details :

0. [eslint v.2.0.0 removed rules](http://eslint.org/docs/user-guide/migrating-to-2.0.0#removed-rules)
0. [rules replacement](http://eslint.org/docs/rules/keyword-spacing.html)

### CODE REVIEW

**Comment by brutalcrozt** [comment]
why it's conflict? i new and git look's so confusing :confused:

**Comment by Gillespie59** [comment]
Don't worry. I am going to merge your PR ;)

**Comment by Gillespie59** [comment]
Thanks

**Comment by brutalcrozt** [comment]
i try rebase and should sqash that 3 to be one, but i can't and don't know why. Maybe because i already push it :confused: .

Thanks to providing good tools

**Pull request merged**
