### PR TITLE
Report any property prefixed with $$ (#203)

### LINKED ISSUE #203: no-private-calls: report any property prefixed with $$
The rule 'no-private-calls' covers 12 predefined properties, but the internal properties and methods can change in any minor or patch release without any mention in the changelog.

If there are any valid usages for $$-prefixed properties or methods, they should be whitelisted.

### PR DESCRIPTION
**Pull request by tilmanpotthof**
Closes #203

### CODE REVIEW

**Comment by Gillespie59** [comment]
Looks like the build failed ;)

**Comment by tilmanpotthof** [comment]
@Gillespie59 Some last second rename broke my test case ;-)

**Comment by Gillespie59** [comment]
I will generate the 0.11.0 release tomorrow night.

**Comment by Gillespie59** [comment]
In fact, I have just pushed the 0.11.0 release. thanks a lot @tilmanpotthof   and @remcohaszing

**Comment by tilmanpotthof** [comment]
Awesome <3

**Pull request merged**
