### PR TITLE
Fix rule di-order for named functions

### LINKED ISSUE #263: Rule di-order is not working if named functions are used in angular components
This should be found by ``di-order``:

````
angular.module('app').factory('myDirective', myDirective);

function myDirective(dependency_b, dependency_a){
} 
````

### PR DESCRIPTION
**Pull request by palortoff**
Fixes #263

### CODE REVIEW

**Comment by remcohaszing** [comment]
I think it's best not to merge this PR, because it fixes a subset of the issues resolved by #257 and it will cause merge conflicts between the two.

**Comment by Gillespie59** [comment]
@remcohaszing is this PR ready to be merged ?

**Comment by remcohaszing** [comment]
@Gillespie No, the issue fixed by this PR fixes has been resolved by #257. So this PR can be closed, but not merged.

**Comment by Gillespie59** [comment]
OK perfect. I close.

**Pull request closed without merging**
