### PR TITLE
Add a rule for setting a component per file limit

### LINKED ISSUE #32: Define 1 component per page (Y001)
https://github.com/johnpapa/angularjs-styleguide

  - Define 1 component per file.

  The following example defines the `app` module and its dependencies, defines a controller, and defines a factory all in the same file.

  ```javascript
  /* avoid */
  angular
      .module('app', ['ngRoute'])
      .controller('SomeController', SomeController)
      .factory('someFactory', someFactory);

  function SomeController() { }

  function someFactory() { }
  ```

  The same components are now separated into their own files.

  ```javascript
  /* recommended */

  // app.module.js
  angular
      .module('app', ['ngRoute']);
  ```

  ```javascript
  /* recommended */

  // someController.js
  angular
      .module('app')
      .controller('SomeController', SomeController);

  function SomeController() { }
  ```

  ```javascript
  /* recommended */

  // someFactory.js
  angular
      .module('app')
      .factory('someFactory', someFactory);

  function someFactory() { }
  ```

### PR DESCRIPTION
**Pull request by remcohaszing**
Closes #32

### CODE REVIEW

**Comment by Gillespie59** [comment]
That's the solution I was talking about @tilmanpotthof 

If we say that we allow m components per file. And in one file we have n components defined.
In fact, I am OK with multiple error messages. But only for the last (n-m) component definitions. 

What do you think ? 

With this solution it is possible to highlight in a IDE all the extra component definitions.

**Comment by tilmanpotthof** [comment]
@remcohaszing You need to merge the current develop, because all lines in the rule documentation section were changed by this PR https://github.com/Gillespie59/eslint-plugin-angular/pull/206/files

**Comment by remcohaszing** [comment]
It can be merged now.

**Comment by tilmanpotthof** [comment]
@Gillespie59 I think it can be merged. Thanks @remcohaszing!!!

**Pull request merged**
