### PR TITLE
Add rule for checking module dependency order

### PR DESCRIPTION
**Pull request by remcohaszing**

### CODE REVIEW

**Comment by Gillespie59** [comment]
In fact iI have some difficulties with the "combined" keyword. 
What about 2 parameters ?
- grouped : true/false
- alphabetically: true/false

**Comment by remcohaszing** [comment]
In both modes the modules should be sorted alphabetically. What about simply:

- grouped: true/false
- prefix: string (only affects if grouped is true).

**Comment by Gillespie59** [comment]
:+1: Thanks

**Comment by Gillespie59** [comment]
Thanks !!

**Pull request merged**
