### PR TITLE
add short link to styleguide in rule section (#288)

### PR DESCRIPTION
**Pull request by tilmanpotthof**
This PR contains only updates to docs and the doc generating script. Therefore I opened a PR to the `master`.

cc @remcohaszing

### CODE REVIEW

**Comment by remcohaszing** [comment]
The patch itself looks fine, but I think a PR to the `development` branch would still be better. It needs to be merged into the `development` branch as well anyway. I wouldn't mind to merge this into `master` from there immediately, as `development` currently isn't ahead of `master`anyway.

**Comment by tilmanpotthof** [comment]
We currently use PRs from `development` to `master` and I wanted to avoid two PRs. The merge direction from `master` to `development` is not critical.

What do you think? @Gillespie59

**Comment by Gillespie59** [comment]
I'll prefer on the `dev` branch. I want the code on the `master` branch exactly similar to the one tagged and pushed on the NPM repo.

**Comment by tilmanpotthof** [comment]
Ok, I understand that. I'll close this PR and reopen one for the development branch.

**Pull request closed without merging**
