### PR TITLE
service-name warn only once if there is an oldBehavior=true

### PR DESCRIPTION
**Pull request by oriSomething**
Related to #431 

Also when there was no `oldBehavior` at all since it's default to `true`
- [ ] Test locally

### CODE REVIEW

**Comment by Gillespie59** [comment]
Any update about this PR ? and about my comment ?

**Comment by oriSomething** [comment]
Sorry, barely have the time, since need to fix the 100% coverage.
If i understood your comment, I've moved it to before the `return` of the `Object` for ESLint traversing

**Comment by Gillespie59** [comment]
But do we need this didWarnForDeprecatedBehavior flag ?

**Comment by oriSomething** [comment]
It's only made for logging the warning only once, and to flood like described in the issue, since the `context` param might changed by different files

**Comment by oriSomething** [comment]
I thought again, If `oldBehavior` is `undefined`, Maybe we should use ESLint warning instead of `console.log`? It won't break parse, and UX for the programmer will be better

**Comment by oriSomething** [comment]
@Gillespie59 This PR is ready, but maybe I should replace the `console.warn` with ESLint warning?

**Comment by Gillespie59** [comment]
But I do not the syntax for ESLint warnings :s

**Comment by oriSomething** [comment]
@Gillespie59 Sorry, I didn't understand

**Comment by Gillespie59** [comment]
With the complete sentence ... sorry
_But I do not know the syntax for ESLint warnings :s. What do you meen by ESLint warning ?_

**Comment by oriSomething** [comment]
Ah, I meant by reporting ESLing warning (as reporting error) like any ESLint errors.
Reporting about "deprecated syntax"

**Comment by mateatslc** [comment]
would be nice to see this move

**Pull request merged**
