### PR TITLE
Karma done

### PR DESCRIPTION
**Pull request by olore**
@Gillespie59 - It's still early, but is this something you'd be interested in as part of eslint-plugin-angular?
I was considering making my own plugin as this is Angular + Jasmine, but figured I would check & see what you thought.

Thanks for the great plugin!

### CODE REVIEW

**Comment by olore** [comment]
Please don't merge this. Just gauging level of interest.

**Comment by Gillespie59** [comment]
Hi.
I am currently out of the office. ;) will have a look to your PR next week
! Thanks

**Comment by Gillespie59** [comment]
Hi 

I have just added few comments on your PR. great job ;)

When your rule is finished, I will be very pleased to merge in this repo ;)

You should to the PR on the **development** branch (not the master one)

Regards

Manu

**Comment by olore** [comment]
Thank you for your comments. I'm really liking the test harness you have set up.  I will decline this and open a new one when it's ready for an initial merge.

**Pull request closed without merging**
