### PR TITLE
Change format eslint to yaml, update dependencies and devDependencies

### PR DESCRIPTION
**Pull request by brutalcrozt**
loadash updated to 4.3.0
eslint v.2.0.0

---
with this details :
  0. [eslint v.2.0.0 removed rules](http://eslint.org/docs/user-guide/migrating-to-2.0.0#removed-rules)
  0. [rules replacement](http://eslint.org/docs/rules/keyword-spacing.html)

### CODE REVIEW

**Comment by brutalcrozt** [comment]
i hope can get some feedback, IDK but i only change 2 file. when i run `gulp`. It show 7k error about line ending. so i have to change it on atom, but not change the rules. maybe when rebasing i intentionally add those file.
if that really necessary, i will do it, but give me some clue hot to do it :sweat_smile:

**Comment by remcohaszing** [comment]
Looks good to me, but I think this is a breaking change.

I'd really like to upgrade to eslint 2.x, so I suggest we include this and release 1.0.0 soon.

**Comment by brutalcrozt** [comment]
any `todo` on 1.0.0 ?
`breaking change` term still confusing for me right now :sweat_smile:

**Comment by remcohaszing** [comment]
A *breaking change* means it's backwards incompatible. [Semver](http://semver.org) specifies these should be included in major versions. Since we're on `0.x.y`, that would be `1.0.0`.

**Comment by brutalcrozt** [comment]
So i should make new PR to `1.0.0` and close this?
i prefer to chat since just a little thing like this, but like no body on gitter :smile:

**Comment by Gillespie59** [comment]
FYI I have just created a branch for that

**Comment by remcohaszing** [comment]
> any todo on 1.0.0 ?
That would be #323

@brutalcrozt 
One remark, could you restore the files where trailing spaces have been added and the ones where the closing newlines have been removed?

**Comment by brutalcrozt** [comment]
@remcohaszing better we ignore it since it just because i use windows line?
am i correct that you request PR without unnecessary file change?

**Comment by remcohaszing** [comment]
> @remcohaszing better we ignore it since it just because i use windows line?

This doesn't seem to be the problem. The changes I'm talking about are about the addition of trailing spaces and the removal of the last newline in some further unchanged files.

> am i correct that you request PR without unnecessary file change?

Yes please, so those would be the changes in `.eslintrc` and `package.json`. and the PR should be to the newly created `1.0` branch.

Oh also, thanks for the PR by the way! :+1:

**Pull request closed without merging**
