### PR TITLE
Revert "Move docs to docs/rules"

### PR DESCRIPTION
**Pull request by Gillespie59**
Reverts Gillespie59/eslint-plugin-angular#496

### CODE REVIEW

**Comment by Gillespie59** [comment]
Could you send another PR on the dev branch ?

**Comment by Gillespie59** [comment]
What do you mean?

**Comment by j-f1** [comment]
See [the `docs` directory](https://github.com/Gillespie59/eslint-plugin-angular/tree/development/docs) on the `development` branch.

**Comment by Gillespie59** [comment]
We now have a docs/rules folder as you proposed in another PR. It was you are looking for, isn't it ? 

This PR was a mistake from my part.

**Pull request merged**
