### PR TITLE
Add new rule for validating DI order

### PR DESCRIPTION
**Pull request by remcohaszing**

### CODE REVIEW

**Comment by Gillespie59** [comment]
Thanks @remcohaszing

**Comment by Gillespie59** [comment]
You are now officially a collaborator to this project. You have the rights for pushing to the repo (on the dev branch of course ;))

**Comment by Gillespie59** [comment]
Can you do it on the right branch ?

**Comment by Gillespie59** [comment]
did not check before merging the PR.

**Comment by remcohaszing** [comment]
Merged #165, which turned out to be fine after all.

**Pull request merged**
